@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Пользователь as usr
participant Frontend as f
participant "Transport Controller" as tc
participant "Transport Mapper" as tm
participant "Transport Service" as ts
participant Database as db

usr -> f: Открытие веб-страницы
f -> tc: Тип, статус аренды,\n парковка транспорта
tc -> ts: Тип, статус аренды,\n парковка транспорта
ts -> db: Запрос информации о транспорте\nпо типу, статусу аренды и парковке
db --> ts: Информация о транспорте\nпо типу, статусу аренды и парковке
ts --> tc: Информация о транспорте\nпо типу, статусу аренды и парковке
tc -> tm: Информация о транспорте\nпо типу, статусу аренды и парковке
tm --> tc: Объект передачи данных\nинформации о транспорте\nпо типу, статусу аренды и парковке
tc --> f: Объект передачи данных\nинформации о транспорте\nпо типу, статусу аренды и парковке
f --> usr: Отображение информации о транспорте\nпо типу, статусу аренды и парковке
@enduml